# Workflow의 이름
name: EC2에 배포하기

on:
  push:
    branches:
      - main

jobs:
  my-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3 # appleboy/ssh-action이라는 오픈소스 GitHub Action을 사용하여 EC2 인스턴스에 SSH로 접속
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }} # EC2의 주소
          username: ${{ secrets.EC2_USERNAME }} # EC2 접속 username
          key: ${{ secrets.EC2_PRIVATE_KEY }} # EC2의 Key 파일의 내부 텍스트
          envs: APPLICATION_PROPERTIES
          script_stop: true # 아래 script 중 실패하는 명령이 하나라도 있으면 실패로 처리
          script: |
            cd /home/ubuntu/cicd_02_boot # 여기 경로는 자신의 EC2에 맞는 경로로 재작성하기
            rm -rf src/main/resources/application.properties
            git pull origin main
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.properties
            chmod +x ./gradlew
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true # || true를 붙인 이유는 8080에 종료시킬 프로세스가 없더라도 실패로 처리하지 않기 위해서이다. 
            
            # jar 파일을 실행시키는 명령어이다. 그리고 발생하는 로그들을 ./output.log 파일에 남기는 명령어이다.
            # nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
            cd build/libs
            nohup java -jar *SNAPSHOT.jar > ./output.log 2>&1 &